import type { ShipItConfig } from './config.js';
import { kebab } from './emit-css.js';
import { isValidCssColor } from './validate.js';

type Section = { lines: string[] };

const formatLine = (cssName: string, value: string | number): string => `  ${cssName}: ${value};`;

const validateColor = (key: string, value: string): void => {
  if (!isValidCssColor(value)) {
    throw new Error(
      `Invalid CSS color for color.${key}: "${value}". Use a hex, rgb/rgba, hsl, oklch, lab/lch, color(), color-mix(), or a CSS color keyword.`,
    );
  }
};

export type EmitOptions = {
  /** Path to the source config file. Embedded as a comment in the output for traceability. */
  sourceConfig?: string;
};

export const emitSparseOverrideCss = (config: ShipItConfig, options: EmitOptions = {}): string => {
  const rootSection: Section = { lines: [] };
  const lightSection: Section = { lines: [] };

  // 1. accent hue knob
  if (typeof config.accentH === 'number') {
    rootSection.lines.push(formatLine('--accent-h', config.accentH));
  }

  // 2. dark color overrides (go on :root since dark is the default theme)
  if (config.color?.dark) {
    for (const [key, value] of Object.entries(config.color.dark)) {
      validateColor(key, value);
      rootSection.lines.push(formatLine(`--color-${kebab(key)}`, value));
    }
  }

  // 3. typography overrides (theme-invariant — emit on :root)
  if (config.typography?.fontFamily) {
    for (const [key, value] of Object.entries(config.typography.fontFamily)) {
      rootSection.lines.push(formatLine(`--font-family-${kebab(key)}`, value));
    }
  }
  if (config.typography?.fontSize) {
    for (const [key, value] of Object.entries(config.typography.fontSize)) {
      rootSection.lines.push(formatLine(`--font-size-${kebab(key)}`, value));
    }
  }
  if (config.typography?.fontWeight) {
    for (const [key, value] of Object.entries(config.typography.fontWeight)) {
      rootSection.lines.push(formatLine(`--font-weight-${kebab(key)}`, value));
    }
  }
  if (config.typography?.lineHeight) {
    for (const [key, value] of Object.entries(config.typography.lineHeight)) {
      rootSection.lines.push(formatLine(`--line-height-${kebab(key)}`, value));
    }
  }
  if (config.typography?.tracking) {
    for (const [key, value] of Object.entries(config.typography.tracking)) {
      rootSection.lines.push(formatLine(`--tracking-${kebab(key)}`, value));
    }
  }

  // 4. light color overrides
  if (config.color?.light) {
    for (const [key, value] of Object.entries(config.color.light)) {
      validateColor(key, value);
      lightSection.lines.push(formatLine(`--color-${kebab(key)}`, value));
    }
  }

  if (rootSection.lines.length === 0 && lightSection.lines.length === 0) return '';

  const header = `/* AUTO-GENERATED by \`shipit build-tokens\` from ${options.sourceConfig ?? 'ship-it.config.ts'} — do not edit by hand. */\n`;

  const parts: string[] = [header];
  if (rootSection.lines.length > 0) {
    parts.push(':root {', ...rootSection.lines, '}');
  }
  if (lightSection.lines.length > 0) {
    if (rootSection.lines.length > 0) parts.push('');
    parts.push("[data-theme='light'] {", ...lightSection.lines, '}');
  }

  return parts.join('\n') + '\n';
};
