/**
 * Public icon exports.
 *
 * The contents of this file (excluding this header) are AUTO-GENERATED by
 * scripts/build.ts from the SVG files under src/svg/. Do not hand-edit.
 *
 * Until the first SVG is added, this file is intentionally empty so the
 * package builds cleanly.
 */

export type { SVGProps } from 'react';
