/**
 * Generates `styles/tokens.css` from the TypeScript token modules.
 *
 * Output structure:
 *
 *   :root           ← light theme + theme-invariant tokens (radius, spacing, …)
 *   .dark, [data-theme="dark"]   ← dark theme overrides
 *
 * Run via `pnpm --filter @ship-it/tokens build` (also runs as part of the
 * top-level `pnpm build`).
 */

import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import {
  breakpoint,
  colorSemanticDark,
  colorSemanticLight,
  duration,
  easing,
  fontFamily,
  fontSize,
  fontWeight,
  letterSpacing,
  lineHeight,
  radius,
  shadowDark,
  shadowLight,
  spacing,
  zIndex,
} from '../src/index.js';

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUTPUT_PATH = resolve(__dirname, '../styles/tokens.css');

export const kebab = (s: string): string => s.replace(/([a-z])([A-Z])/g, '$1-$2').toLowerCase();

type TokenValue = string | number;

export const block = (prefix: string, obj: Record<string, TokenValue>): string =>
  Object.entries(obj)
    .map(([k, v]) => `  --${prefix}-${kebab(String(k))}: ${v};`)
    .join('\n');

export const buildTokenCss = (): string => {
  const lightVars = [
    '/* Color (semantic, light theme) */',
    block('color', colorSemanticLight),
    '',
    '/* Shadow (light theme) */',
    block('shadow', shadowLight),
    '',
    '/* Font family */',
    block('font-family', fontFamily),
    '',
    '/* Font size */',
    block('font-size', fontSize),
    '',
    '/* Font weight */',
    block('font-weight', fontWeight),
    '',
    '/* Line height */',
    block('line-height', lineHeight),
    '',
    '/* Letter spacing */',
    block('letter-spacing', letterSpacing),
    '',
    '/* Spacing */',
    block('space', spacing),
    '',
    '/* Radius */',
    block('radius', radius),
    '',
    '/* Motion: duration */',
    block('duration', duration),
    '',
    '/* Motion: easing */',
    block('easing', easing),
    '',
    '/* Breakpoints (informational; Tailwind reads its own config) */',
    block('breakpoint', breakpoint),
    '',
    '/* Z-index */',
    block('z', zIndex),
  ].join('\n');

  const darkVars = [
    '/* Color (semantic, dark theme) */',
    block('color', colorSemanticDark),
    '',
    '/* Shadow (dark theme) */',
    block('shadow', shadowDark),
  ].join('\n');

  return `/* AUTO-GENERATED by scripts/build-css.ts — do not edit by hand. */

:root {
${lightVars}
}

.dark,
[data-theme='dark'] {
${darkVars}
}

@media (prefers-reduced-motion: reduce) {
  :root {
    --duration-fast: 0ms;
    --duration-base: 0ms;
    --duration-slow: 0ms;
    --duration-deliberate: 0ms;
  }
}
`;
};

export const writeTokenCss = (outputPath = OUTPUT_PATH): void => {
  mkdirSync(dirname(outputPath), { recursive: true });
  writeFileSync(outputPath, buildTokenCss(), 'utf8');
  console.log(`✓ tokens.css written → ${outputPath}`);
};

/* v8 ignore next 3 */
if (process.argv[1] === fileURLToPath(import.meta.url)) {
  writeTokenCss();
}
