/**
 * Generates `styles/tokens.css` from the TypeScript token modules.
 *
 * Emission shape (intentionally matches the handoff's `colors_and_type.css`):
 *
 *   :root {
 *     --accent-h: 200;          // master hue knob
 *     // dark theme + theme-invariant tokens (radius, spacing, motion, type, …)
 *   }
 *
 *   [data-theme='light'] {
 *     // light theme overrides ONLY (color + shadow)
 *   }
 *
 *   @media (prefers-reduced-motion: reduce) {
 *     :root { --duration-micro: 0ms; --duration-step: 0ms; }
 *   }
 *
 * Run via `pnpm --filter @ship-it/tokens build` (also part of top-level `pnpm build`).
 */

import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import {
  accentH,
  breakpoint,
  colorSemanticDark,
  colorSemanticLight,
  duration,
  easing,
  elevation,
  fontFamily,
  fontSize,
  fontWeight,
  lineHeight,
  radius,
  shadowDark,
  shadowLight,
  spacing,
  tracking,
  zIndex,
} from '../src/index.js';

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUTPUT_PATH = resolve(__dirname, '../styles/tokens.css');

// camelCase → kebab-case. Keep digits attached to the preceding letter so `h4`
// stays `h4`, not `h-4`. Only insert a hyphen at lowercase→uppercase boundaries.
const kebab = (s: string) => s.replace(/([a-z])([A-Z])/g, '$1-$2').toLowerCase();

type TokenValue = string | number;

/**
 * Emit a block of CSS variables.
 *   block('color', { bg: '#000', textMuted: '#888' })
 *     --color-bg: #000;
 *     --color-text-muted: #888;
 */
const block = (prefix: string, obj: Record<string, TokenValue>): string =>
  Object.entries(obj)
    .map(([k, v]) => `  --${prefix}-${kebab(String(k))}: ${v};`)
    .join('\n');

/**
 * Shadow is special: handoff uses `--shadow` (no suffix) for the base level, plus
 * `--shadow-sm` and `--shadow-lg`. So we emit them explicitly rather than via block().
 */
const shadowBlock = (s: typeof shadowDark): string =>
  [`  --shadow-sm: ${s.sm};`, `  --shadow: ${s.base};`, `  --shadow-lg: ${s.lg};`].join('\n');

const root = [
  '  /* Master accent hue — override at runtime to reskin */',
  `  --accent-h: ${accentH};`,
  '',
  '  /* Color (semantic, dark theme — default) */',
  block('color', colorSemanticDark),
  '',
  '  /* Shadow (dark recipe) */',
  shadowBlock(shadowDark),
  '',
  '  /* Typography — families */',
  block('font-family', fontFamily),
  '',
  '  /* Typography — sizes */',
  block('font-size', fontSize),
  '',
  '  /* Typography — weights */',
  block('font-weight', fontWeight),
  '',
  '  /* Typography — line-heights */',
  block('line-height', lineHeight),
  '',
  '  /* Typography — tracking */',
  block('tracking', tracking),
  '',
  '  /* Spacing (4pt base, irregular ramp — handoff skips 7) */',
  block('space', spacing),
  '',
  '  /* Radius */',
  block('radius', radius),
  '',
  '  /* Motion — durations */',
  block('duration', duration),
  '',
  '  /* Motion — easings */',
  block('easing', easing),
  '',
  '  /* Elevation accents (inset highlights for elevated dark surfaces) */',
  `  --elevation-inset-highlight: ${elevation.insetHighlightDark};`,
  '',
  '  /* Breakpoints (informational; Tailwind reads its own config) */',
  block('breakpoint', breakpoint),
  '',
  '  /* Z-index */',
  block('z', zIndex),
].join('\n');

const lightOverrides = [
  '  /* Color (semantic, light theme — overrides only) */',
  block('color', colorSemanticLight),
  '',
  '  /* Shadow (light recipe) */',
  shadowBlock(shadowLight),
  '',
  '  /* Elevation: inset highlight is invisible on light surfaces, zero it out */',
  `  --elevation-inset-highlight: ${elevation.insetHighlightLight};`,
].join('\n');

const css = `/* AUTO-GENERATED by scripts/build-css.ts — do not edit by hand. */

:root {
${root}
}

[data-theme='light'] {
${lightOverrides}
}

@media (prefers-reduced-motion: reduce) {
  :root {
    --duration-micro: 0ms;
    --duration-step: 0ms;
  }
}
`;

mkdirSync(dirname(OUTPUT_PATH), { recursive: true });
writeFileSync(OUTPUT_PATH, css, 'utf8');
console.log(`✓ tokens.css written → ${OUTPUT_PATH}`);
