/**
 * Reads the icon manifest (`src/icon-manifest.ts`), pulls each referenced
 * Iconify icon from the corresponding `@iconify-json/*` devDep, and writes
 * `src/icon-data.ts` — a typed `Record<string, { body; viewBox; width; height }>`
 * that ships as the runtime data source for `<IconGlyph>` and
 * `iconToSvgDataUrl()`.
 *
 * The output file is *committed* (same convention as `src/svg-icons.ts` from
 * `scripts/build.ts`). A `vitest` drift test in `src/icon-data.test.ts`
 * regenerates the same content in-memory and byte-diffs against the committed
 * copy so the manifest never silently desyncs from the data.
 *
 * Run via `pnpm --filter @ship-it-ui/icons build` (part of the standard build
 * sequence) or directly: `pnpm --filter @ship-it-ui/icons exec tsx scripts/build-icon-data.ts`.
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { getIconData, iconToSVG } from '@iconify/utils';
import { format as prettierFormat, resolveConfig as prettierResolveConfig } from 'prettier';

import { glyphManifest, logoManifest, type IconRef } from '../src/icon-manifest';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ICON_DATA_FILE = resolve(__dirname, '../src/icon-data.ts');

export interface IconBody {
  body: string;
  viewBox: string;
  width: number;
  height: number;
}

const header = `// AUTO-GENERATED by scripts/build-icon-data.ts — do not edit by hand.\n// Re-run \`pnpm --filter @ship-it-ui/icons build\` after editing src/icon-manifest.ts.\n`;

/**
 * Lazy-load each `@iconify-json/<collection>` package via `require` so the
 * codegen pulls only the collections actually referenced by the manifest.
 * Iconify ships each collection as a single JSON blob (~1–5MB), so this also
 * keeps the resolved devDep set small if the manifest later drops a collection.
 */
const require_ = createRequire(import.meta.url);
const collectionCache = new Map<string, ReturnType<typeof require_>>();
function loadCollection(name: string): ReturnType<typeof require_> {
  const cached = collectionCache.get(name);
  if (cached) return cached;
  const pkg = require_(`@iconify-json/${name}/icons.json`);
  collectionCache.set(name, pkg);
  return pkg;
}

export function resolveIcon([collection, icon]: IconRef): IconBody {
  const data = loadCollection(collection);
  const iconData = getIconData(data, icon);
  if (!iconData) {
    throw new Error(
      `Icon "${icon}" not found in collection "${collection}". ` +
        `Check the manifest entry or browse https://icon-sets.iconify.design/${collection}/ for valid names.`,
    );
  }
  const rendered = iconToSVG(iconData, { width: 'auto', height: 'auto' });
  const width = Number(rendered.attributes.width);
  const height = Number(rendered.attributes.height);
  return {
    body: rendered.body,
    viewBox: rendered.attributes.viewBox,
    width: Number.isFinite(width) ? width : 24,
    height: Number.isFinite(height) ? height : 24,
  };
}

/** Build the full icon-data record from both manifests. */
export function buildIconData(): Record<string, IconBody> {
  const out: Record<string, IconBody> = {};
  const errors: string[] = [];
  for (const [name, ref] of Object.entries(glyphManifest)) {
    try {
      out[name] = resolveIcon(ref);
    } catch (err) {
      errors.push(`glyph "${name}" → ${(err as Error).message}`);
    }
  }
  for (const [name, ref] of Object.entries(logoManifest)) {
    try {
      out[`logo:${name}`] = resolveIcon(ref);
    } catch (err) {
      errors.push(`logo "${name}" → ${(err as Error).message}`);
    }
  }
  if (errors.length > 0) {
    throw new Error(
      `Icon manifest failed to resolve ${errors.length} entries:\n  ${errors.join('\n  ')}`,
    );
  }
  return out;
}

export function renderIconDataModule(data: Record<string, IconBody>): string {
  const sortedKeys = Object.keys(data).sort();
  const entries = sortedKeys
    .map((key) => {
      const v = data[key]!;
      // Stringify with stable key order. `body` is the raw SVG body — emit it
      // as a single-line string so the diff stays readable on manifest edits.
      const body = JSON.stringify(v.body);
      const viewBox = JSON.stringify(v.viewBox);
      return (
        `  ${JSON.stringify(key)}: {\n` +
        `    body: ${body},\n` +
        `    viewBox: ${viewBox},\n` +
        `    width: ${v.width},\n` +
        `    height: ${v.height},\n` +
        `  },`
      );
    })
    .join('\n');
  return (
    `${header}\n` +
    `export interface IconData {\n` +
    `  /** Raw SVG body (children of the <svg> element). */\n` +
    `  body: string;\n` +
    `  /** Intrinsic viewBox (e.g. "0 0 24 24"). */\n` +
    `  viewBox: string;\n` +
    `  /** Intrinsic width in viewBox units. */\n` +
    `  width: number;\n` +
    `  /** Intrinsic height in viewBox units. */\n` +
    `  height: number;\n` +
    `}\n\n` +
    `export const iconData: Record<string, IconData> = {\n${entries}\n};\n`
  );
}

/**
 * Format the rendered TS source through the project's Prettier config so the
 * committed file is byte-identical to what the drift test regenerates.
 * Without this, `JSON.stringify` output (double quotes, quoted keys) diverges
 * from the Prettier-formatted on-disk file (`singleQuote: true`, unquoted
 * identifier keys) and the drift test fails on CI.
 */
export async function formatIconData(
  target: string,
  data: Record<string, IconBody>,
): Promise<string> {
  const rendered = renderIconDataModule(data);
  const config = await prettierResolveConfig(target);
  return prettierFormat(rendered, {
    ...config,
    parser: 'typescript',
    filepath: target,
  });
}

export async function writeIconData(target: string = ICON_DATA_FILE): Promise<void> {
  const data = buildIconData();
  const formatted = await formatIconData(target, data);
  writeFileSync(target, formatted, 'utf8');
  // eslint-disable-next-line no-console
  console.log(`✓ Generated ${Object.keys(data).length} icons → ${target}`);
}

/** Read the on-disk icon-data.ts and return its full source. */
export function readIconData(source: string = ICON_DATA_FILE): string {
  return readFileSync(source, 'utf8');
}

/* v8 ignore next 3 */
if (process.argv[1] === fileURLToPath(import.meta.url)) {
  await writeIconData();
}
