/**
 * Reads every `*.svg` under `src/svg/`, transforms each into a typed React
 * component via SVGR, writes them to `src/components/`, and rewrites
 * `src/svg-icons.ts` to re-export them.
 *
 * The main `src/index.ts` imports from `./svg-icons` so we never clobber the
 * manually-authored exports (IconGlyph, glyphs, etc).
 *
 * Generated component names are PascalCase + "Icon" suffix:
 *   src/svg/arrow-right.svg → ArrowRightIcon (in src/components/ArrowRightIcon.tsx)
 *
 * Run via `pnpm --filter @ship-it-ui/icons build` (also part of top-level build).
 */

import { mkdirSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { transform } from '@svgr/core';

const __dirname = dirname(fileURLToPath(import.meta.url));
const SVG_DIR = resolve(__dirname, '../src/svg');
const OUT_DIR = resolve(__dirname, '../src/components');
const SVG_INDEX = resolve(__dirname, '../src/svg-icons.ts');

export const toPascal = (s: string): string =>
  s
    .replace(/\.svg$/i, '')
    .split(/[-_\s]+/)
    .filter(Boolean)
    .map((w) => w[0]!.toUpperCase() + w.slice(1).toLowerCase())
    .join('');

export const svgrConfig = {
  plugins: ['@svgr/plugin-svgo', '@svgr/plugin-jsx'],
  typescript: true,
  jsxRuntime: 'automatic' as const,
  expandProps: 'end' as const,
  svgProps: { width: '1em', height: '1em', fill: 'currentColor', 'aria-hidden': 'true' },
  replaceAttrValues: { '#000': 'currentColor', '#000000': 'currentColor' },
};

export interface BuildIconsOptions {
  svgDir?: string;
  outDir?: string;
  indexFile?: string;
}

const header = `// AUTO-GENERATED by scripts/build.ts — do not edit by hand.\n// Re-run \`pnpm --filter @ship-it-ui/icons build\` after adding/removing SVGs.\n`;

export const emptyIndexSource = `${header}export {};\n`;

export const buildIcons = async ({
  svgDir = SVG_DIR,
  outDir = OUT_DIR,
  indexFile = SVG_INDEX,
}: BuildIconsOptions = {}): Promise<number> => {
  mkdirSync(outDir, { recursive: true });

  const svgFiles = readdirSync(svgDir).filter((f) => f.endsWith('.svg'));

  if (svgFiles.length === 0) {
    // Reset svg-icons.ts so the package still builds with no SVGs.
    writeFileSync(indexFile, emptyIndexSource, 'utf8');
    console.log('No SVGs found in src/svg/. svg-icons.ts reset.');
    return 0;
  }

  const exports: string[] = [];
  for (const file of svgFiles) {
    const svg = readFileSync(resolve(svgDir, file), 'utf8');
    const componentName = `${toPascal(file)}Icon`;
    const tsx = await transform(svg, svgrConfig, { componentName });
    writeFileSync(resolve(outDir, `${componentName}.tsx`), tsx, 'utf8');
    exports.push(`export { default as ${componentName} } from './components/${componentName}';`);
  }

  writeFileSync(indexFile, `${header}${exports.sort().join('\n')}\n`, 'utf8');
  console.log(`✓ Generated ${svgFiles.length} icon component(s).`);
  return svgFiles.length;
};

/* v8 ignore next 3 */
if (process.argv[1] === fileURLToPath(import.meta.url)) {
  await buildIcons();
}
