/**
 * Walks `apps/docs-site/examples/**` and emits `.generated/examples.ts`:
 *
 *   export const examples = {
 *     'button/primary': { Component: lazy(() => import(...)), source: '...' },
 *     …
 *   };
 *
 * The registry is the single bridge between MDX (which references slugs) and
 * the actual example components + their raw source. We embed the source as a
 * string literal — more reliable than relying on a webpack `?raw` rule, and it
 * works the same in dev, prod, and static export.
 *
 * Run via `predev` / `prebuild` in `apps/docs-site/package.json`.
 */
import { mkdirSync, readFileSync, readdirSync, statSync, writeFileSync } from 'node:fs';
import { dirname, join, relative } from 'node:path';

const ROOT = process.cwd();
const EXAMPLES_DIR = join(ROOT, 'examples');
const OUT_DIR = join(ROOT, '.generated');
const OUT_FILE = join(OUT_DIR, 'examples.ts');

interface Entry {
  slug: string;
  importPath: string;
  source: string;
}

function walk(dir: string, out: Entry[] = []): Entry[] {
  for (const name of readdirSync(dir)) {
    const abs = join(dir, name);
    if (statSync(abs).isDirectory()) {
      walk(abs, out);
    } else if (name.endsWith('.tsx')) {
      const rel = relative(EXAMPLES_DIR, abs)
        .replace(/\\/g, '/')
        .replace(/\.tsx$/, '');
      const importPath = `../examples/${rel}`;
      const source = readFileSync(abs, 'utf8');
      out.push({ slug: rel, importPath, source });
    }
  }
  return out;
}

function main() {
  let entries: Entry[] = [];
  try {
    entries = walk(EXAMPLES_DIR).sort((a, b) => a.slug.localeCompare(b.slug));
  } catch (err: unknown) {
    if ((err as { code?: string }).code !== 'ENOENT') throw err;
  }

  const lines: string[] = [];
  lines.push('// AUTO-GENERATED by scripts/build-examples-registry.ts. Do not edit.');
  lines.push("import { lazy, type ComponentType } from 'react';");
  lines.push('');
  lines.push('export interface ExampleEntry {');
  lines.push('  Component: ComponentType;');
  lines.push('  source: string;');
  lines.push('}');
  lines.push('');
  lines.push('export const examples: Record<string, ExampleEntry> = {');
  for (const e of entries) {
    const escaped = e.source.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$/g, '\\$');
    lines.push(`  ${JSON.stringify(e.slug)}: {`);
    lines.push(`    Component: lazy(() => import(${JSON.stringify(e.importPath)})),`);
    lines.push(`    source: \`${escaped}\`,`);
    lines.push('  },');
  }
  lines.push('};');
  lines.push('');

  mkdirSync(dirname(OUT_FILE), { recursive: true });
  writeFileSync(OUT_FILE, lines.join('\n'), 'utf8');
  console.log(`[examples-registry] wrote ${entries.length} entries → ${relative(ROOT, OUT_FILE)}`);
}

main();
